language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0

env:
  matrix:
    - DEPENDENCIES=""
    - DEPENDENCIES="--prefer-lowest --prefer-stable"

before_script:
  - composer self-update
  - composer update $DEPENDENCIES
